export const courses = [
{slug:'desenvolvimento-de-sistemas',name:'Desenvolvimento de Sistemas',category:'Técnico',duration:'18 meses',area:'Tecnologia',description:'Transforme ideias em soluções. Aprenda a projetar, desenvolver e testar aplicações que conectam pessoas.',topics:['Lógica de programação','Bancos de dados','Desenvolvimento web','Projetos integradores']},
{slug:'quimica',name:'Química',category:'Técnico',duration:'24 meses',area:'Ciência',description:'Descubra a ciência por trás dos materiais e dos processos. Da bancada do laboratório às aplicações industriais.',topics:['Química geral','Análise laboratorial','Processos industriais','Segurança em laboratório']},
{slug:'eletromecanica',name:'Eletromecânica',category:'Técnico',duration:'24 meses',area:'Indústria',description:'Conecte sistemas elétricos e mecânicos para construir uma indústria mais inteligente.',topics:['Eletricidade','Mecânica aplicada','Automação','Manutenção industrial']},
{slug:'instrumentacao-industrial',name:'Instrumentação Industrial',category:'Técnico',duration:'18 meses',area:'Indústria',description:'Aprenda a medir, controlar e otimizar os processos que movem a indústria.',topics:['Metrologia','Sensores','Controle de processos','Instrumentação']},
{slug:'croche',name:'Crochê',category:'Curso livre',duration:'3 meses',area:'Criação',description:'Crie com as próprias mãos. Desenvolva técnicas, explore texturas e transforme criatividade em possibilidades.',topics:['Pontos fundamentais','Leitura de receitas','Acabamento','Projeto autoral']},
{slug:'python',name:'Python',category:'Minicurso',duration:'40 horas',area:'Tecnologia',description:'Dê o primeiro passo na programação com projetos práticos em Python.',topics:['Fundamentos','Estruturas de dados','Funções','Automação simples']},
{slug:'excel-pro',name:'Excel Pro',category:'Minicurso',duration:'40 horas',area:'Negócios',description:'Organize dados e construa análises que ajudam a tomar decisões.',topics:['Fórmulas','Tabelas dinâmicas','Gráficos','Análise de dados']},
...['Sistemas de Informação','Engenharia de Software','Engenharia Química','Engenharia Mecatrônica','Administração'].map((name,i)=>({name,slug:['sistemas-de-informacao','engenharia-de-software','engenharia-quimica','engenharia-mecatronica','administracao'][i],category:'Graduação',duration:'Consulte a grade',area:i===4?'Negócios':i===2?'Ciência':'Tecnologia',description:'Uma formação superior que une conhecimento, prática e visão de futuro. Construa sua trajetória com projetos interdisciplinares.',topics:['Fundamentos da área','Projetos interdisciplinares','Formação profissional','Projeto de conclusão']}))
];
export const articles=[{slug:'conexoes-que-transformam',tag:'Vida no campus',title:'Conexões que transformam o jeito de aprender.',text:'Espaços colaborativos aproximam estudantes de diferentes áreas para desenvolver projetos em conjunto.'},{slug:'feira-de-profissoes',tag:'Eventos',title:'Encontre caminhos na Feira de Profissões Nexus.',text:'Uma programação demonstrativa com oficinas, conversas sobre carreira e experiências de aprendizagem.'},{slug:'laboratorio-de-ideias',tag:'Inovação',title:'Do laboratório de ideias ao primeiro projeto.',text:'Conheça a proposta de uma jornada prática que começa com uma pergunta e termina com uma solução.'}];
