export type Field={key:string,label:string,type?:'text'|'textarea'|'number'|'date'|'url'|'select'|'checkbox',options?:string[],reference?:string,required?:boolean};
export type Module={table:string,title:string,description:string,roles:string[],writers:string[],fields:Field[]};
const all=['student','teacher','guardian','admin','director'];const staff=['admin','director'];const teaching=['teacher',...staff];
export const modules:Record<string,Module>={
'cadastros':{table:'profiles',title:'Pessoas e aprovações',description:'Analise solicitações e acompanhe as pessoas da Nexus.',roles:staff,writers:[],fields:[{key:'name',label:'Nome'},{key:'role',label:'Perfil'},{key:'status',label:'Situação'},{key:'ra',label:'RA'},{key:'requested_course',label:'Curso solicitado'},{key:'scholarship',label:'Interesse em bolsa'}]},
'cursos':{table:'courses',title:'Cursos',description:'Organize a oferta acadêmica.',roles:staff,writers:staff,fields:[{key:'title',label:'Curso',required:true},{key:'category',label:'Categoria',type:'select',options:['Técnico','Graduação','Curso livre','Minicurso']},{key:'duration',label:'Duração',required:true},{key:'description',label:'Descrição',type:'textarea'},{key:'published',label:'Publicado',type:'checkbox'}]},
'turmas':{table:'classes',title:'Turmas',description:'Sua comunidade de aprendizagem.',roles:all,writers:staff,fields:[{key:'title',label:'Turma',required:true},{key:'course_id',label:'Curso',reference:'courses',required:true},{key:'period',label:'Período',type:'select',options:['Manhã','Tarde','Noite','Online','Híbrido']}]},
'matriculas':{table:'enrollments',title:'Matrículas',description:'Vincule alunos às turmas.',roles:staff,writers:staff,fields:[{key:'student_id',label:'Aluno',reference:'students',required:true},{key:'class_id',label:'Turma',reference:'classes',required:true}]},
'professores':{table:'class_teachers',title:'Atribuição de professores',description:'Defina as turmas sob responsabilidade de cada professor.',roles:staff,writers:staff,fields:[{key:'teacher_id',label:'Professor',reference:'teachers',required:true},{key:'class_id',label:'Turma',reference:'classes',required:true}]},
'responsaveis':{table:'guardian_students',title:'Vínculos de responsáveis',description:'Somente vínculos cadastrados aqui liberam acesso ao aluno.',roles:staff,writers:staff,fields:[{key:'guardian_id',label:'Responsável',reference:'guardians',required:true},{key:'student_id',label:'Aluno',reference:'students',required:true}]},
'disciplinas':{table:'subjects',title:'Disciplinas',description:'Conheça os componentes da sua formação.',roles:all,writers:teaching,fields:[{key:'title',label:'Disciplina',required:true},{key:'class_id',label:'Turma',reference:'classes',required:true}]},
'notas':{table:'grades',title:'Notas e boletim',description:'Acompanhe o desenvolvimento acadêmico.',roles:all,writers:teaching,fields:[{key:'student_id',label:'Aluno',reference:'students',required:true},{key:'class_id',label:'Turma',reference:'classes',required:true},{key:'subject',label:'Disciplina',required:true},{key:'title',label:'Avaliação',required:true},{key:'score',label:'Nota (0–10)',type:'number',required:true}]},
'frequencia':{table:'attendance',title:'Frequência e chamada',description:'Presença faz parte da sua trajetória.',roles:all,writers:teaching,fields:[{key:'student_id',label:'Aluno',reference:'students',required:true},{key:'class_id',label:'Turma',reference:'classes',required:true},{key:'lesson_date',label:'Data da aula',type:'date',required:true},{key:'status',label:'Presença',type:'select',options:['Presente','Falta','Justificada']}]},
'horarios':{table:'schedules',title:'Horários',description:'Organize seu dia de estudos.',roles:all,writers:teaching,fields:[{key:'title',label:'Aula',required:true},{key:'class_id',label:'Turma',reference:'classes',required:true},{key:'day',label:'Dia',type:'select',options:['Segunda','Terça','Quarta','Quinta','Sexta','Sábado']},{key:'time',label:'Horário',required:true},{key:'location',label:'Sala ou local',required:true}]},
'atividades':{table:'assignments',title:'Atividades',description:'Desafios para colocar seu aprendizado em prática.',roles:all,writers:teaching,fields:[{key:'title',label:'Atividade',required:true},{key:'class_id',label:'Turma',reference:'classes',required:true},{key:'description',label:'Orientações',type:'textarea',required:true},{key:'due_at',label:'Prazo',type:'date',required:true}]},
'entregas':{table:'submissions',title:'Entregas',description:'Envie sua resposta e acompanhe as entregas.',roles:all,writers:['student'],fields:[{key:'assignment_id',label:'Atividade',reference:'assignments',required:true},{key:'content',label:'Sua resposta',type:'textarea',required:true}]},
'materiais':{table:'materials',title:'Materiais de estudo',description:'Recursos para aprofundar o conhecimento.',roles:all,writers:teaching,fields:[{key:'title',label:'Material',required:true},{key:'class_id',label:'Turma',reference:'classes',required:true},{key:'description',label:'Descrição',type:'textarea'},{key:'url',label:'Link HTTPS',type:'url',required:true}]},
'comunicados':{table:'announcements',title:'Comunicados',description:'Informações importantes da sua comunidade.',roles:all,writers:teaching,fields:[{key:'title',label:'Assunto',required:true},{key:'class_id',label:'Turma (vazio = geral)',reference:'classes'},{key:'description',label:'Mensagem',type:'textarea',required:true}]},
'calendario':{table:'events',title:'Calendário',description:'Os próximos encontros e acontecimentos.',roles:all,writers:staff,fields:[{key:'title',label:'Evento',required:true},{key:'description',label:'Descrição',type:'textarea',required:true},{key:'event_date',label:'Data',type:'date',required:true},{key:'published',label:'Publicado',type:'checkbox'}]},
'conteudo':{table:'posts',title:'Blog e mural',description:'Compartilhe notícias e experiências.',roles:staff,writers:staff,fields:[{key:'title',label:'Título',required:true},{key:'description',label:'Conteúdo',type:'textarea',required:true},{key:'category',label:'Categoria',type:'select',options:['Blog','Mural','Notícia','Visita técnica']},{key:'published',label:'Publicado',type:'checkbox'}]},
'solicitacoes':{table:'academic_requests',title:'Solicitações',description:'Converse com a secretaria e acompanhe suas solicitações.',roles:all,writers:all,fields:[{key:'title',label:'Assunto',required:true},{key:'description',label:'Como podemos ajudar?',type:'textarea',required:true},{key:'status',label:'Situação'},{key:'response',label:'Resposta'}]},
'certificados':{table:'certificates',title:'Documentos e certificados',description:'Documentos demonstrativos, sem validade acadêmica oficial.',roles:all,writers:staff,fields:[{key:'student_id',label:'Aluno',reference:'students',required:true},{key:'title',label:'Documento',required:true},{key:'description',label:'Conteúdo',type:'textarea',required:true}]},
'auditoria':{table:'audit_logs',title:'Auditoria',description:'Registro de alterações no sistema, acessível somente à direção.',roles:['director'],writers:[],fields:[{key:'created_at',label:'Data'},{key:'action',label:'Ação'},{key:'entity',label:'Entidade'},{key:'record_id',label:'Registro'}]}
};
export const roleLabels:Record<string,string>={student:'Aluno',teacher:'Professor',guardian:'Responsável',admin:'Gestão',director:'Direção'};
