create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;
create sequence public.student_ra_seq start 10001;
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade, name text not null check(length(name) between 2 and 120), role text not null default 'student' check(role in ('student','teacher','guardian','admin','director')), status text not null default 'pending' check(status in ('pending','approved','rejected','suspended')), ra text unique, created_at timestamptz not null default now());
create table public.courses(id uuid primary key default gen_random_uuid(),title text not null, category text not null, duration text not null, description text not null default '',published boolean not null default false,created_at timestamptz not null default now());
create table public.classes(id uuid primary key default gen_random_uuid(),title text not null,course_id uuid not null references public.courses(id),period text not null,created_at timestamptz not null default now());
create table public.enrollments(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.profiles(id),class_id uuid not null references public.classes(id),created_at timestamptz not null default now(),unique(student_id,class_id));
create table public.class_teachers(id uuid primary key default gen_random_uuid(),teacher_id uuid not null references public.profiles(id),class_id uuid not null references public.classes(id),created_at timestamptz not null default now(),unique(teacher_id,class_id));
create table public.guardian_students(id uuid primary key default gen_random_uuid(),guardian_id uuid not null references public.profiles(id),student_id uuid not null references public.profiles(id),created_at timestamptz not null default now(),unique(guardian_id,student_id),check(guardian_id<>student_id));
create table public.subjects(id uuid primary key default gen_random_uuid(),title text not null,class_id uuid not null references public.classes(id),created_at timestamptz not null default now());
create table public.grades(id uuid primary key default gen_random_uuid(),student_id uuid not null,class_id uuid not null,subject text not null,title text not null,score numeric not null check(score between 0 and 10),created_at timestamptz not null default now(),foreign key(student_id,class_id) references public.enrollments(student_id,class_id));
create table public.attendance(id uuid primary key default gen_random_uuid(),student_id uuid not null,class_id uuid not null,lesson_date date not null,status text not null check(status in ('Presente','Falta','Justificada')),created_at timestamptz not null default now(),foreign key(student_id,class_id) references public.enrollments(student_id,class_id),unique(student_id,class_id,lesson_date));
create table public.materials(id uuid primary key default gen_random_uuid(),class_id uuid not null references public.classes(id),title text not null,description text not null default '',url text not null check(url ~ '^https://'),created_at timestamptz not null default now());
create table public.assignments(id uuid primary key default gen_random_uuid(),class_id uuid not null references public.classes(id),title text not null,description text not null,due_at date not null,created_at timestamptz not null default now());
create table public.submissions(id uuid primary key default gen_random_uuid(),assignment_id uuid not null references public.assignments(id),student_id uuid not null references public.profiles(id),content text not null check(length(content) between 1 and 10000),created_at timestamptz not null default now(),unique(assignment_id,student_id));
create table public.schedules(id uuid primary key default gen_random_uuid(),class_id uuid not null references public.classes(id),title text not null,day text not null,time text not null,location text not null,created_at timestamptz not null default now());
create table public.announcements(id uuid primary key default gen_random_uuid(),class_id uuid references public.classes(id),title text not null,description text not null,created_at timestamptz not null default now());
create table public.events(id uuid primary key default gen_random_uuid(),title text not null,description text not null,event_date date not null,published boolean not null default false,created_at timestamptz not null default now());
create table public.posts(id uuid primary key default gen_random_uuid(),title text not null,description text not null,category text not null,published boolean not null default false,created_at timestamptz not null default now());
create table public.academic_requests(id uuid primary key default gen_random_uuid(),owner_id uuid not null references public.profiles(id),title text not null,description text not null,status text not null default 'Aberta' check(status in ('Aberta','Em análise','Concluída')),response text not null default '',created_at timestamptz not null default now());
create table public.certificates(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.profiles(id),title text not null,description text not null,created_at timestamptz not null default now());
create table public.audit_logs(id uuid primary key default gen_random_uuid(),actor_id uuid,action text not null,entity text not null,record_id uuid,created_at timestamptz not null default now());
-- Internal lookups deliberately bypass recursive RLS. No public RPC exposure,
-- no parameters selecting a caller, fixed search_path, and auth.uid() required.
create function private.my_role() returns text language sql stable security definer set search_path='' as $$ select role from public.profiles where id=(select auth.uid()) and status='approved' and (select auth.uid()) is not null $$;
create function private.is_staff() returns boolean language sql stable security invoker set search_path='' as $$select coalesce(private.my_role() in ('admin','director'),false)$$;
create function private.teaches(c uuid) returns boolean language sql stable security definer set search_path='' as $$select (select auth.uid()) is not null and private.my_role()='teacher' and exists(select 1 from public.class_teachers where class_id=c and teacher_id=(select auth.uid()))$$;
create function private.related(s uuid) returns boolean language sql stable security definer set search_path='' as $$select (select auth.uid()) is not null and (private.is_staff() or (private.my_role()='student' and s=(select auth.uid())) or (private.my_role()='guardian' and exists(select 1 from public.guardian_students where guardian_id=(select auth.uid()) and student_id=s)))$$;
create function private.in_class(c uuid) returns boolean language sql stable security definer set search_path='' as $$select (select auth.uid()) is not null and (private.is_staff() or private.teaches(c) or exists(select 1 from public.enrollments e where e.class_id=c and private.related(e.student_id)))$$;
create function private.sees_student(s uuid) returns boolean language sql stable security definer set search_path='' as $$select (select auth.uid()) is not null and (private.related(s) or exists(select 1 from public.enrollments e where e.student_id=s and private.teaches(e.class_id)))$$;
revoke all on all functions in schema private from public,anon;
grant execute on all functions in schema private to authenticated;
-- Signup trigger ignores user-supplied roles, status and RA.
create function private.on_signup() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(id,name) values(new.id,left(coalesce(nullif(new.raw_user_meta_data->>'name',''),'Estudante Nexus'),120));return new;end$$;
revoke all on function private.on_signup() from public,anon,authenticated;
create trigger nexus_signup after insert on auth.users for each row execute function private.on_signup();
create function private.audit() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.audit_logs(actor_id,action,entity,record_id) values(auth.uid(),TG_OP,TG_TABLE_NAME,coalesce(new.id,old.id));return coalesce(new,old);end$$;
revoke all on function private.audit() from public,anon,authenticated;
create function private.profile_guard() returns trigger language plpgsql security invoker set search_path='' as $$begin
 if auth.uid() is not null and private.my_role() <> 'director' and (old.role in ('director','admin') or new.role in ('director','admin') or old.id=auth.uid()) then raise exception 'Somente a direção pode alterar gestores';end if;
 if new.role='student' and new.status='approved' and new.ra is null then new.ra='NS'||to_char(now(),'YYYY')||lpad(nextval('public.student_ra_seq')::text,6,'0');end if;return new;end$$;
revoke all on function private.profile_guard() from public,anon,authenticated;
create trigger guard_profile before update on public.profiles for each row execute function private.profile_guard();
alter table public.profiles enable row level security;
revoke all on public.profiles from anon,authenticated;
grant select,insert,update,delete on public.profiles to authenticated;
grant all on public.profiles to service_role;
create trigger audit_profiles after insert or update or delete on public.profiles for each row execute function private.audit();
alter table public.courses enable row level security;
revoke all on public.courses from anon,authenticated;
grant select,insert,update,delete on public.courses to authenticated;
grant all on public.courses to service_role;
create trigger audit_courses after insert or update or delete on public.courses for each row execute function private.audit();
alter table public.classes enable row level security;
revoke all on public.classes from anon,authenticated;
grant select,insert,update,delete on public.classes to authenticated;
grant all on public.classes to service_role;
create trigger audit_classes after insert or update or delete on public.classes for each row execute function private.audit();
alter table public.enrollments enable row level security;
revoke all on public.enrollments from anon,authenticated;
grant select,insert,update,delete on public.enrollments to authenticated;
grant all on public.enrollments to service_role;
create trigger audit_enrollments after insert or update or delete on public.enrollments for each row execute function private.audit();
alter table public.class_teachers enable row level security;
revoke all on public.class_teachers from anon,authenticated;
grant select,insert,update,delete on public.class_teachers to authenticated;
grant all on public.class_teachers to service_role;
create trigger audit_class_teachers after insert or update or delete on public.class_teachers for each row execute function private.audit();
alter table public.guardian_students enable row level security;
revoke all on public.guardian_students from anon,authenticated;
grant select,insert,update,delete on public.guardian_students to authenticated;
grant all on public.guardian_students to service_role;
create trigger audit_guardian_students after insert or update or delete on public.guardian_students for each row execute function private.audit();
alter table public.subjects enable row level security;
revoke all on public.subjects from anon,authenticated;
grant select,insert,update,delete on public.subjects to authenticated;
grant all on public.subjects to service_role;
create trigger audit_subjects after insert or update or delete on public.subjects for each row execute function private.audit();
alter table public.grades enable row level security;
revoke all on public.grades from anon,authenticated;
grant select,insert,update,delete on public.grades to authenticated;
grant all on public.grades to service_role;
create trigger audit_grades after insert or update or delete on public.grades for each row execute function private.audit();
alter table public.attendance enable row level security;
revoke all on public.attendance from anon,authenticated;
grant select,insert,update,delete on public.attendance to authenticated;
grant all on public.attendance to service_role;
create trigger audit_attendance after insert or update or delete on public.attendance for each row execute function private.audit();
alter table public.materials enable row level security;
revoke all on public.materials from anon,authenticated;
grant select,insert,update,delete on public.materials to authenticated;
grant all on public.materials to service_role;
create trigger audit_materials after insert or update or delete on public.materials for each row execute function private.audit();
alter table public.assignments enable row level security;
revoke all on public.assignments from anon,authenticated;
grant select,insert,update,delete on public.assignments to authenticated;
grant all on public.assignments to service_role;
create trigger audit_assignments after insert or update or delete on public.assignments for each row execute function private.audit();
alter table public.submissions enable row level security;
revoke all on public.submissions from anon,authenticated;
grant select,insert,update,delete on public.submissions to authenticated;
grant all on public.submissions to service_role;
create trigger audit_submissions after insert or update or delete on public.submissions for each row execute function private.audit();
alter table public.schedules enable row level security;
revoke all on public.schedules from anon,authenticated;
grant select,insert,update,delete on public.schedules to authenticated;
grant all on public.schedules to service_role;
create trigger audit_schedules after insert or update or delete on public.schedules for each row execute function private.audit();
alter table public.announcements enable row level security;
revoke all on public.announcements from anon,authenticated;
grant select,insert,update,delete on public.announcements to authenticated;
grant all on public.announcements to service_role;
create trigger audit_announcements after insert or update or delete on public.announcements for each row execute function private.audit();
alter table public.events enable row level security;
revoke all on public.events from anon,authenticated;
grant select,insert,update,delete on public.events to authenticated;
grant all on public.events to service_role;
create trigger audit_events after insert or update or delete on public.events for each row execute function private.audit();
alter table public.posts enable row level security;
revoke all on public.posts from anon,authenticated;
grant select,insert,update,delete on public.posts to authenticated;
grant all on public.posts to service_role;
create trigger audit_posts after insert or update or delete on public.posts for each row execute function private.audit();
alter table public.academic_requests enable row level security;
revoke all on public.academic_requests from anon,authenticated;
grant select,insert,update,delete on public.academic_requests to authenticated;
grant all on public.academic_requests to service_role;
create trigger audit_academic_requests after insert or update or delete on public.academic_requests for each row execute function private.audit();
alter table public.certificates enable row level security;
revoke all on public.certificates from anon,authenticated;
grant select,insert,update,delete on public.certificates to authenticated;
grant all on public.certificates to service_role;
create trigger audit_certificates after insert or update or delete on public.certificates for each row execute function private.audit();
alter table public.audit_logs enable row level security;
revoke all on public.audit_logs from anon,authenticated;
grant select,insert,update,delete on public.audit_logs to authenticated;
grant all on public.audit_logs to service_role;
grant usage,select on sequence public.student_ra_seq to authenticated,service_role;
create policy read_profiles on public.profiles for select to authenticated using (id=(select auth.uid()) or private.sees_student(id));
create policy update_profiles on public.profiles for update to authenticated using (private.is_staff()) with check (private.is_staff());
create policy read_courses on public.courses for select to authenticated using (published or private.is_staff());
create policy insert_courses on public.courses for insert to authenticated with check (private.is_staff());
create policy update_courses on public.courses for update to authenticated using (private.is_staff()) with check (private.is_staff());
create policy delete_courses on public.courses for delete to authenticated using (private.is_staff());
create policy read_classes on public.classes for select to authenticated using (private.in_class(id));
create policy insert_classes on public.classes for insert to authenticated with check (private.is_staff());
create policy update_classes on public.classes for update to authenticated using (private.is_staff()) with check (private.is_staff());
create policy delete_classes on public.classes for delete to authenticated using (private.is_staff());
create policy read_enrollments on public.enrollments for select to authenticated using (private.sees_student(student_id));
create policy insert_enrollments on public.enrollments for insert to authenticated with check (private.is_staff());
create policy update_enrollments on public.enrollments for update to authenticated using (private.is_staff()) with check (private.is_staff());
create policy delete_enrollments on public.enrollments for delete to authenticated using (private.is_staff());
create policy read_class_teachers on public.class_teachers for select to authenticated using (teacher_id=(select auth.uid()) or private.is_staff());
create policy insert_class_teachers on public.class_teachers for insert to authenticated with check (private.is_staff());
create policy update_class_teachers on public.class_teachers for update to authenticated using (private.is_staff()) with check (private.is_staff());
create policy delete_class_teachers on public.class_teachers for delete to authenticated using (private.is_staff());
create policy read_guardian_students on public.guardian_students for select to authenticated using (guardian_id=(select auth.uid()) or private.is_staff());
create policy insert_guardian_students on public.guardian_students for insert to authenticated with check (private.is_staff());
create policy update_guardian_students on public.guardian_students for update to authenticated using (private.is_staff()) with check (private.is_staff());
create policy delete_guardian_students on public.guardian_students for delete to authenticated using (private.is_staff());
create policy read_subjects on public.subjects for select to authenticated using (private.in_class(class_id));
create policy insert_subjects on public.subjects for insert to authenticated with check (private.is_staff() or private.teaches(class_id));
create policy update_subjects on public.subjects for update to authenticated using (private.is_staff() or private.teaches(class_id)) with check (private.is_staff() or private.teaches(class_id));
create policy delete_subjects on public.subjects for delete to authenticated using (private.is_staff() or private.teaches(class_id));
create policy read_materials on public.materials for select to authenticated using (private.in_class(class_id));
create policy insert_materials on public.materials for insert to authenticated with check (private.is_staff() or private.teaches(class_id));
create policy update_materials on public.materials for update to authenticated using (private.is_staff() or private.teaches(class_id)) with check (private.is_staff() or private.teaches(class_id));
create policy delete_materials on public.materials for delete to authenticated using (private.is_staff() or private.teaches(class_id));
create policy read_assignments on public.assignments for select to authenticated using (private.in_class(class_id));
create policy insert_assignments on public.assignments for insert to authenticated with check (private.is_staff() or private.teaches(class_id));
create policy update_assignments on public.assignments for update to authenticated using (private.is_staff() or private.teaches(class_id)) with check (private.is_staff() or private.teaches(class_id));
create policy delete_assignments on public.assignments for delete to authenticated using (private.is_staff() or private.teaches(class_id));
create policy read_schedules on public.schedules for select to authenticated using (private.in_class(class_id));
create policy insert_schedules on public.schedules for insert to authenticated with check (private.is_staff() or private.teaches(class_id));
create policy update_schedules on public.schedules for update to authenticated using (private.is_staff() or private.teaches(class_id)) with check (private.is_staff() or private.teaches(class_id));
create policy delete_schedules on public.schedules for delete to authenticated using (private.is_staff() or private.teaches(class_id));
create policy read_grades on public.grades for select to authenticated using (private.related(student_id) or private.teaches(class_id));
create policy insert_grades on public.grades for insert to authenticated with check (private.is_staff() or private.teaches(class_id));
create policy update_grades on public.grades for update to authenticated using (private.is_staff() or private.teaches(class_id)) with check (private.is_staff() or private.teaches(class_id));
create policy delete_grades on public.grades for delete to authenticated using (private.is_staff() or private.teaches(class_id));
create policy read_attendance on public.attendance for select to authenticated using (private.related(student_id) or private.teaches(class_id));
create policy insert_attendance on public.attendance for insert to authenticated with check (private.is_staff() or private.teaches(class_id));
create policy update_attendance on public.attendance for update to authenticated using (private.is_staff() or private.teaches(class_id)) with check (private.is_staff() or private.teaches(class_id));
create policy delete_attendance on public.attendance for delete to authenticated using (private.is_staff() or private.teaches(class_id));
create policy read_announcements on public.announcements for select to authenticated using ((class_id is null and private.my_role() is not null) or private.in_class(class_id));
create policy insert_announcements on public.announcements for insert to authenticated with check (private.is_staff() or (class_id is not null and private.teaches(class_id)));
create policy update_announcements on public.announcements for update to authenticated using (private.is_staff() or (class_id is not null and private.teaches(class_id))) with check (private.is_staff() or (class_id is not null and private.teaches(class_id)));
create policy delete_announcements on public.announcements for delete to authenticated using (private.is_staff() or (class_id is not null and private.teaches(class_id)));
create policy read_posts on public.posts for select to authenticated using (published or private.is_staff());
create policy insert_posts on public.posts for insert to authenticated with check (private.is_staff());
create policy update_posts on public.posts for update to authenticated using (private.is_staff()) with check (private.is_staff());
create policy delete_posts on public.posts for delete to authenticated using (private.is_staff());
create policy read_events on public.events for select to authenticated using (published or private.is_staff());
create policy insert_events on public.events for insert to authenticated with check (private.is_staff());
create policy update_events on public.events for update to authenticated using (private.is_staff()) with check (private.is_staff());
create policy delete_events on public.events for delete to authenticated using (private.is_staff());
grant select on public.courses to anon;
create policy public_courses on public.courses for select to anon using(published);
grant select on public.events to anon;
create policy public_events on public.events for select to anon using(published);
grant select on public.posts to anon;
create policy public_posts on public.posts for select to anon using(published);
create policy read_certificates on public.certificates for select to authenticated using (private.related(student_id));
create policy insert_certificates on public.certificates for insert to authenticated with check (private.is_staff());
create policy update_certificates on public.certificates for update to authenticated using (private.is_staff()) with check (private.is_staff());
create policy delete_certificates on public.certificates for delete to authenticated using (private.is_staff());
create policy read_audit_logs on public.audit_logs for select to authenticated using (private.my_role()='director');
create policy read_academic_requests on public.academic_requests for select to authenticated using (owner_id=(select auth.uid()) or private.is_staff());
create policy insert_requests on public.academic_requests for insert to authenticated with check(owner_id=(select auth.uid()) and private.my_role() is not null and status='Aberta' and response='');
create policy update_requests on public.academic_requests for update to authenticated using(private.is_staff()) with check(private.is_staff());
create policy read_submissions on public.submissions for select to authenticated using (private.related(student_id) or exists(select 1 from public.assignments a where a.id=assignment_id and private.teaches(a.class_id)));
create policy insert_submissions on public.submissions for insert to authenticated with check(student_id=(select auth.uid()) and private.my_role()='student' and exists(select 1 from public.assignments a join public.enrollments e on e.class_id=a.class_id where a.id=assignment_id and e.student_id=(select auth.uid()) and a.due_at>=current_date));
create index classes_course_id_idx on public.classes(course_id);
create index enrollments_class_id_idx on public.enrollments(class_id);
create index class_teachers_class_id_idx on public.class_teachers(class_id);
create index guardian_students_student_id_idx on public.guardian_students(student_id);
create index subjects_class_id_idx on public.subjects(class_id);
create index grades_student_id_idx on public.grades(student_id);
create index grades_class_id_idx on public.grades(class_id);
create index attendance_student_id_idx on public.attendance(student_id);
create index attendance_class_id_idx on public.attendance(class_id);
create index materials_class_id_idx on public.materials(class_id);
create index assignments_class_id_idx on public.assignments(class_id);
create index submissions_student_id_idx on public.submissions(student_id);
create index schedules_class_id_idx on public.schedules(class_id);
create index announcements_class_id_idx on public.announcements(class_id);
create index academic_requests_owner_id_idx on public.academic_requests(owner_id);
create index certificates_student_id_idx on public.certificates(student_id);
