import {createClient} from 'npm:@supabase/supabase-js@2.116.0';
const url=Deno.env.get('SUPABASE_URL')!;const secret=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const anon=Deno.env.get('SUPABASE_ANON_KEY')!;
const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Content-Type':'application/json','Cache-Control':'no-store'};
function reply(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers})}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers});if(req.method!=='POST')return reply({error:'Método não permitido'},405);try{if(Number(req.headers.get('content-length')||0)>20000)return reply({error:'Requisição muito grande'},413);const body=await req.json();const admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});
if(body.action==='ra-login'){
 // Custom password authentication: the gateway only returns a session after GoTrue validates credentials.
 const ra=String(body.ra||'').trim().toUpperCase();const password=String(body.password||'');if(!/^NS[0-9]{10}$/.test(ra)||password.length<1||password.length>128)return reply({error:'Credenciais inválidas'},401);
 const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(ra));const key=Array.from(new Uint8Array(digest)).map(x=>x.toString(16).padStart(2,'0')).join('');
 const{data:allowed,error:limitError}=await admin.rpc('consume_login_attempt',{k:key});if(limitError||!allowed)return reply({error:'Tente novamente mais tarde'},429);
 const{data:student}=await admin.from('profiles').select('id').eq('ra',ra).eq('status','approved').eq('role','student').maybeSingle();const identity=student?await admin.auth.admin.getUserById(student.id):null;const email=identity?.data?.user?.email;const auth=createClient(url,anon,{auth:{persistSession:false,autoRefreshToken:false}});const{data,error}=await auth.auth.signInWithPassword({email:email||'unknown@nexus.invalid',password});if(error||!data.session)return reply({error:'Credenciais inválidas'},401);return reply({access_token:data.session.access_token,refresh_token:data.session.refresh_token});}
 const token=req.headers.get('authorization')?.replace(/^Bearer /i,'');if(!token)return reply({error:'Acesso negado'},401);const{data:{user},error:authError}=await admin.auth.getUser(token);if(authError||!user)return reply({error:'Acesso negado'},401);const{data:actor}=await admin.from('profiles').select('role,status').eq('id',user.id).single();if(actor?.status!=='approved'||!['admin','director'].includes(actor.role))return reply({error:'Acesso negado'},403);
 if(body.action==='create-account'){const role=String(body.role);if(!['teacher','guardian','admin'].includes(role)||role==='admin'&&actor.role!=='director')return reply({error:'Perfil não permitido'},403);const name=String(body.name||'').trim();const email=String(body.email||'').trim();if(name.length<2||name.length>120||!/^\S+@\S+\.\S+$/.test(email))return reply({error:'Dados inválidos'},400);
 const{data,error}=await admin.auth.admin.inviteUserByEmail(email,{data:{name}});if(error||!data.user)return reply({error:'Não foi possível criar o acesso. Verifique o endereço e a configuração de envio.'},400);const{error:updateError}=await admin.from('profiles').update({role,status:'approved'}).eq('id',data.user.id);if(updateError){await admin.auth.admin.deleteUser(data.user.id);return reply({error:'Não foi possível atribuir o perfil'},500)}await admin.from('audit_logs').insert({actor_id:user.id,action:'CREATE_ACCOUNT',entity:'profiles',record_id:data.user.id});return reply({message:'Conta criada. Um convite de ativação foi enviado.'});}
 return reply({error:'Operação inválida'},400);
}catch{return reply({error:'Não foi possível concluir a operação'},400)}});
